### PR TITLE
adding functionality to resize background image in real-time

### PR DESCRIPTION
**Pull request by pseiler**
* check if there are more monitors than one connected and resize the image giving in the argument.
* if the monitors doesn't have the same resolution, write a error message to stdout and use the base image instead

### CODE REVIEW

**Comment by SammysHP** [comment]
Thanks, I reviewed it really quickly and have some remarks (for example "missing" bashisms, handling of multi-monitor configuration, checks, error handling). I'll do a more in-depth review in the next days and will probably rewrite some of the code.

**Comment by pseiler** [comment]
Thank you for the fast reply. Looking forward to see your changes

**Comment by SammysHP** [comment]
I'm sure the README syntax issue is a regression in the markdown parser used by GitHub.

Currently I am working on various background image options (fill/maximize/…). You can see the progress in this branch: https://github.com/SammysHP/i3lockmore/tree/image-fill

**Comment by SammysHP** [comment]
I added this in 189bcca51b04d03db3ccdf7d4127ed616d823350. Please try `--image-fill path` and `--image-maximize path` (see README for differences).

Thanks for your idea nevertheless! I cherry-picked your README fix.

**Pull request closed without merging**
